server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                   #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                    #mysql驱动包
    url: jdbc:mysql://39.107.49.169:3308/litemall                     #数据库连接
    username: root
    password: root
    dbcp2:
      min-idle: 5                                                   #数据库连接池的最小维持连接数
      initial-size: 5                                               #初始化连接数
      max-total: 5                                                  #最大连接数
      max-wait-millis: 200                                          #等待连接获取的最大超时时间
  mybatis:
    mapperLocations: classpath:/mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    typeAliasesPackage: com.minimall.user.domain.entity  # 注意：对应实体类的路径
    configLocation: classpath:/mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always

