server:
  port: 10870
spring:
  application:
    name: admin-server
  profiles:
    active: secure
  security:
    user:
      name: admin
      password: admin
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                   #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                    #mysql驱动包
    url: jdbc:mysql://39.107.49.169:3308/litemall                     #数据库连接
    username: root
    password: root
    dbcp2:
      min-idle: 5                                                   #数据库连接池的最小维持连接数
      initial-size: 5                                               #初始化连接数
      max-total: 5                                                  #最大连接数
      max-wait-millis: 200

eureka:
  instance:
    hostname: localhost
    health-check-url-path: /actuator/health
    instance-id: ${spring.cloud.client.ip-address}-${server.port}
    prefer-ip-address: false
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

litemall:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: xxxxxx
      bucketName: litemall
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: litemall
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall
