eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul-server
zuul:
  prefix: /wx # 设置一个公共的前缀
  routes:
    api-a:
      path: /base/**
      serviceId: base-server
    api-b:
      path: /user/**
      serviceId: user-server
    api-c:
      path: /notify/**
      serviceId: notify-server
    api-d:
      path: /activity/**
      serviceId: activity-server
    api-e:
      path: /commont/**
      serviceId: commont-server
    api-f:
      path: /order/**
      serviceId: order-server
    api-g:
      path: /search/**
      serviceId: search-server
    api-h:
      path: /admin/**
      serviceId: admin-server


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
