server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                   #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                    #mysql驱动包
    url: jdbc:mysql://39.107.49.169:3308/litemall                     #数据库连接
    username: root
    password: root
    dbcp2:
      min-idle: 5                                                   #数据库连接池的最小维持连接数
      initial-size: 5                                               #初始化连接数
      max-total: 5                                                  #最大连接数
      max-wait-millis: 200                                          #等待连接获取的最大超时时间
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always

minimall:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wx48b26326caf0cc43
    app-secret: 31d6ba9f66eb4d35ddb66cf5b2d22718
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx
